export module Enums;

export enum Tasks
{
	CREATE_SHOP_ITEMS = 1,
	SHOW_SHOP_ITEMS,
	DELETE_SHOP_ITEMS,
	EDIT_SHOP_ITEM,
	SAVE_SHOP_ITEMS,
	IMPORT_SHOP_ITEMS,
	CREATE_EMPLOYEES,
	SHOW_EMPLOYEES,
	DELETE_EMPLOYEES,
	EDIT_EMPLOYEE,
	SAVE_EMPLOYEES,
	IMPORT_EMPLOYEES
};
